# Generated by Django 5.0.4 on 2024-05-31 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
                ('Month', models.IntegerField()),
                ('Date', models.CharField(max_length=15)),
                ('Temperature', models.IntegerField()),
                ('meteorologicalConditions', models.CharField(max_length=300)),
                ('windSpeedInKM', models.IntegerField()),
                ('sunriseInAM', models.IntegerField()),
                ('sunsetInPM', models.IntegerField()),
            ],
        ),
    ]
